import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import InitInterceptor from "./providers/InitInterceptor";
import ToasterProvider from "@/components/ToasterProvider";

export const metadata: Metadata = {
  title: "Bugs Star Admin",
  description: "Generated by create next app",
  icons: {
    icon: "/bugs_star_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-foreground">
        <Providers>
          <InitInterceptor />
          {children}
          <ToasterProvider />
        </Providers>
      </body>
    </html>
  );
}
